### ISSUE TITLE
doesn't run

### ISSUE THREAD

**Issue by nullonesix** [Shengjiewang-Jason/EfficientZeroV2#1]
followed installation instructions exactly without issue but the code still doesn't run:

```
(ezv2) swarms@dpm10:~/EfficientZeroV2$ python ez/train.py exp_config=ez/config/exp/atari.yaml
Traceback (most recent call last):
  File "ez/train.py", line 25, in <module>
    from ez import agents
  File "/home/swarms/EfficientZeroV2/ez/agents/__init__.py", line 6, in <module>
    from ez.agents.ez_atari import EZAtariAgent
  File "/home/swarms/EfficientZeroV2/ez/agents/ez_atari.py", line 10, in <module>
    from ez.agents.base import Agent
  File "/home/swarms/EfficientZeroV2/ez/agents/base.py", line 28, in <module>
    from ez.utils.loss import kl_loss, cosine_similarity_loss, continuous_loss, symlog_loss, Value_loss
  File "/home/swarms/EfficientZeroV2/ez/utils/loss.py", line 7, in <module>
    import torchrl
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/__init__.py", line 32, in <module>
    import torchrl.collectors
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/collectors/collectors.py", line 33, in <module>
    from torchrl.data.tensor_specs import TensorSpec
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/__init__.py", line 7, in <module>
    from .replay_buffers import (
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 20, in <module>
    from .samplers import PrioritizedSampler, RandomSampler, Sampler
  File "/home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/samplers.py", line 13, in <module>
    from torchrl._torchrl import (
ImportError: /home/swarms/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/_torchrl.so: undefined symbol: _ZN2at4_ops5clamp4callERKNS_6TensorERKN3c108optionalINS5_6ScalarEEESA_
```

**Comment by Shengjiewang-Jason** [comment]
Hi, can you provide your torch and torchrl version?

**Comment by nullonesix** [comment]
Name: torch
Version: 2.4.0

Name: torchrl
Version: 0.5.0

**Comment by Shengjiewang-Jason** [comment]
oh, I see. The torchrl verion we use is 0.1.0, and you can see the specific info in the requirements.txt

**Comment by nullonesix** [comment]
the problem persists

```
(ezv2) nullonesix@zen:/mnt/c/Users/nullo/Documents/EfficientZeroV2$ pip show torchrl
Name: torchrl
Version: 0.1.0
Summary: UNKNOWN
Home-page: https://github.com/pytorch/rl
Author: torchrl contributors
Author-email: vmoens@fb.com
License: BSD
Location: /home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages
Requires: cloudpickle, numpy, packaging, tensordict, torch
Required-by:
(ezv2) nullonesix@zen:/mnt/c/Users/nullo/Documents/EfficientZeroV2$ python ez/train.py exp_config=ez/config/exp/atari.yaml
Traceback (most recent call last):
  File "ez/train.py", line 25, in <module>
    from ez import agents
  File "/mnt/c/Users/nullo/Documents/EfficientZeroV2/ez/agents/__init__.py", line 6, in <module>
    from ez.agents.ez_atari import EZAtariAgent
  File "/mnt/c/Users/nullo/Documents/EfficientZeroV2/ez/agents/ez_atari.py", line 10, in <module>
    from ez.agents.base import Agent
  File "/mnt/c/Users/nullo/Documents/EfficientZeroV2/ez/agents/base.py", line 28, in <module>
    from ez.utils.loss import kl_loss, cosine_similarity_loss, continuous_loss, symlog_loss, Value_loss
  File "/mnt/c/Users/nullo/Documents/EfficientZeroV2/ez/utils/loss.py", line 7, in <module>
    import torchrl
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/__init__.py", line 32, in <module>
    import torchrl.collectors
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/collectors/collectors.py", line 33, in <module>
    from torchrl.data.tensor_specs import TensorSpec
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/__init__.py", line 7, in <module>
    from .replay_buffers import (
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 20, in <module>
    from .samplers import PrioritizedSampler, RandomSampler, Sampler
  File "/home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/data/replay_buffers/samplers.py", line 13, in <module>
    from torchrl._torchrl import (
ImportError: /home/nullonesix/miniconda3/envs/ezv2/lib/python3.8/site-packages/torchrl/_torchrl.so: undefined symbol: _ZN2at4_ops5clamp4callERKNS_6TensorERKN3c108optionalINS5_6ScalarEEESA_
```

**Comment by Shengjiewang-Jason** [comment]
Ok, I see. You can run ``sh make.sh`` in ``ori_ctree`` folder.  I will remove this line in cy_mcts.py, coz it isn't used.
